mode: local

name: merchant
version: v0.1

zone: India

server:
  http:
    host: 0.0.0.0
    port: 8099

jwt:
  secret: secret
  token_expire: 24
  issuer: alex
  sub: bz

log:
  log_level: debug
  log_dir: ./log
  log_prefix: merchant
  max_size : 30

data:
  mysql-merchant:
    host: 192.168.152.129
    port: 3306
    user: root
    password: 123456
    database: merchant
    max_idle: 20
    max_open: 20
    max_life_time: 300
  redis-merchant:
    addr: 192.168.152.129:6379
    password:
    database: 0
    max_active: 50
  clickhouse-log:
    host: 192.168.152.129
    port: 9000
    database: log
    user: default
    password: 123456
    timeout_connect: 2
    timeout_query: 4

# nsq
nsq:
  addr: 192.168.1.22:4150
  lookUpdAddr:
    - 192.168.1.22:4161